#!/usr/bin/bash
shopt -s extglob
export LC_COLLATE=C

<<COMMENT
	Function to check if the dir exitst "it will cd to it" or not 		"create the dir and cd to it"
COMMENT

function check_dir(){
	
	if [[ -d "$1" ]]
	then
		echo "Databases folder is found"
	else
		mkdir -p "$1"
	fi

}
##########################################################################
