#! /usr/bin/bash
# Checking where Table Name Passed To Function or Not 

if [[ $# -eq 0 ]];
then 
echo "Syntax Error, Creat Command Must Take First Argument Representing Table Name "
else 
	
	if [[ $# -eq 1 ]];
	then
	echo "Syntax Error, Creat Command Must Take at Least One Second Argument Representing Column Name" 

	# Checking Where Database is active to use or no data base persist
	else
		if [[ -e $HOME/$DB ]];
		then
			# Checking The Table that are creating is already persist or not if no the table will be created 

			if [[ -e $HOME/$DB/$1 ]];
			then 
			echo "This Table Already Exist, Change Table Name"
			else 

				if [[ ${@:2:$#-1} =~ [a-zA-Z]+$ ]];
				then

					declare -A arr				# declaring associative array to check wether the passed column are unique or not 
					duplicatefound=false			# if the value of duplicatefound is false this means that there is no duplication in column names
					
					for i in ${@:2:$#-1}; 			# Iterate through the column names
					do 	
    					if [[ -n ${arr[$i]} ]]; 		# Check if the column name is already in the associative array
					then
       					duplicatefound=true
      				 	echo "Syntax Error, Not Accepted to Enter Two or more Columns with Similar Names "
     				   	break
  				  	fi
  				  	arr[$i]=1 				# Mark this column name as seen
					done

					if [[ $duplicatefound == false ]]; 	# If no duplicates are found, create the table
					then
					touch $HOME/$DB/$1
					echo "$1 Table has been Created "	# Telling User That Table is created with the name given (First Argument)
					echo ${@:2:$#-1} > $HOME/$DB/$1
					fi

				else 
				echo "Syntax Error, Not Accepted to Enter Column Name Other than String "
				fi					# Using From the Second argument passed to the last argument as columns names
			fi
		else
		echo "There is No Database called $DB "		# If the data base are not selected using use command it tells user that database is not exist
		fi
	fi
fi

