#! /usr/bin/bash
if [[ $# -eq 0 ]];
then 
echo "Syntax Error, Use Function Must Take One Argument Representng Your Database !! "
elif [[ $# -gt 1 ]];
then 
echo "Syntax Error, Use Function Takes Only One Argument !! "
else
	if [[ -d $HOME/DBMS_Project/Databases/$DB ]];
	then
		export DB=$1
		echo "You are Using $1 Database"
	else
		echo "Error, There Is No Database Called $1"
	fi
fi
